language: android
jdk: oraclejdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26

install:
    - sudo apt update
    - sudo apt install nodejs
    - sudo apt install npm
    - npm config set strict-ssl false
    - sudo npm cache clean -f
    - sudo npm install -g n
    - sudo n stable
    - sudo npm install -g appium@1.9.1

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - mvn clean verify
