os: osx
language: android
android:
  components:
  - build-tools-28.0.2
  - android-25
  - sys-img-x86-android-25
install:
  - brew install awscli
  - npm install -g appium@1.9.1

before_script:
 - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

script:
  mvn clean verify
