language: android
jdk: oraclejdk11

env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.1.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - sys-img-x86-android-25
    - sys-img-armeabi-v7a-android-25
    - extra-google-google_play_services

install:
    - sudo apt-get update
    - sudo apt-get install build-essential libssl-dev
    - sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - source ~/.profile
    - nvm --version
    - nvm install 8.10.0
    - nvm use 8.10.0
    - node -v
    - npm -v
#    - npm config set strict-ssl false
#    - sudo npm cache clean -f
#    - sudo npm install -g n
    - npm install -g appium@1.9.1
#    - cd /AndroidProj1
#    - sudo dpkg -i shashlik_0.9.3.deb
#    - /opt/shashlik/bin/shashlik-install Notepad.apk

before_script:
#  - emulator -list-avds
  - android list targets
  - echo no | android create avd --force -n Default -t android-25 --abi armeabi-v7a --device default&
  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
    - appium --log-level error &
    - mvn clean verify
